### ISSUE TITLE
Please add A/B Test metadata capture to UABot sessions.

### ISSUE THREAD

**Issue by coveoben** [coveo/uabot#72]
### Expected behavior
When a session's query/click activity is routed to an A/B test, I would expect that the UABot would detect the name and version metadata (splitTestRunName and splitTestRunVersion) associated with the transaction and report in the associated UA events.

### Actual behavior
The UABot detects the pipeline through which the query is routed and reports that properly, but the aforementioned metadata are left empty. It is my understanding that the splitTestRunVersion should be the same as the pipeline when there is an A/B test.

### Steps to reproduce the behavior

1. Create a pair of pipelines in Coveo UA and associate them with an A/B test. Be sure there are no other conditions which might cause one or the other pipelines to be invoked.
2. Create a UABot script which specifies one of the pipelines in the A/B test and run that script.
3. Validate that the script is generating statistics including transactions on both pipelines which are in the A/B tests, although only one of those pipelines is specified, indicating that the UABot is detecting the A/B routing appropriately. This validation is done by filtering your reports on the "Query Pipeline".
4. Filter the same activity using the A/B Test filters (name/version), and note that none of that UABot transactions show up.

**Comment by erocheleau** [comment]
This has been merged in master branch and should now be supported!
