### ISSUE TITLE
Check click action docNo out-of-bounds panic error.

### ISSUE THREAD

**Issue by coveoben** [coveo/uabot#75]
### Expected behavior
Not crashing? ;)

I don't believe the behavior is documented, so I don't have a specific expectation, but I'd suggest that when docNo value is set to N (where N>0) for a click on a query which does not have at least N results, the click action should just be skipped.

That said, I could accept an argument that the last extant listing be clicked on, but I think this is not quite as good a behavior.

### Actual behavior
If a scenario is set with a static docNo of N, and a search query returns R results, and N > R, we get a panic/quit due to an array out of bounds error. Here's an example:

```INFO | 2017/06/13 14:00:38 New visit from paul.morris@strongit.com
INFO | 2017/06/13 14:00:38 Language of visit : de
INFO | 2017/06/13 14:00:38 Executing scenario named : GQ -> C(40%)
INFO | 2017/06/13 14:00:38 Searching for : school
INFO | 2017/06/13 14:00:38 Sending Search Event with 6 results

Request response error (400): {"message":"Parameter 'searchEvent.splitTestRunName' must be provided if searchEvent.splitTestRunVersion is provided.","type":"InvalidParameter"}
INFO | 2017/06/13 14:00:38 Sending ClickEvent rank=7 (quickview false)
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x25ab20, 0xc42000a0e0)
	C:/Go/src/runtime/panic.go:500 +0x1a1
github.com/coveo/uabot/scenariolib.(*Visit).sendClickEvent(0xc420110820, 0x6, 0x0, 0x0, 0x3, 0xc42000b589)
	C:/Users/erocheleau/Documents/!GoWorkspace/src/github.com/coveo/uabot/scenariolib/visit.go:325 +0x1246
github.com/coveo/uabot/scenariolib.(*ClickEvent).Execute(0xc4201760c0, 0xc420110820, 0x3b0940, 0xc4201760c0)
	C:/Users/erocheleau/Documents/!GoWorkspace/src/github.com/coveo/uabot/scenariolib/event_click.go:119 +0x2c8
github.com/coveo/uabot/scenariolib.(*Visit).ExecuteScenario(0xc420110820, 0xc42000b9c0, 0xc, 0xa, 0x2b2655, 0x6e, 0xc4200184e0, 0x3, 0x4, 0x0, ...)
	C:/Users/erocheleau/Documents/!GoWorkspace/src/github.com/coveo/uabot/scenariolib/visit.go:129 +0x138
github.com/coveo/uabot/scenariolib.(*uabot).Run(0xc420014870, 0xc4200182a0, 0xc4200182a0, 0x1)
	C:/Users/erocheleau/Documents/!GoWorkspace/src/github.com/coveo/uabot/scenariolib/uabot.go:99 +0x270
main.main()
	C:/Users/erocheleau/Documents/!GoWorkspace/src/github.com/coveo/uabot/main.go:40 +0x612
```

### Steps to reproduce the behavior
In your click, configurations, set your docNo to a static number, as in:

```        {
          "type": "Click",
          "arguments": {
            "docNo": 9,
            "offset": 0,
            "probability": 0.6
          }
        }
```
And then configure a query which returns fewer results than the number you've set. Run your test, and when that scenario runs, the application will quit.

This does not appear to be an issue for searches which return zero results, although I haven't gone out of my way to explicitly test this.

**Comment by coveoben** [comment]
BTW, you can ignore the `splitTestRunName` error included in the above. For one, I know that was my own issue. For another thing, it didn't cause the system to crash. The crashing error occurred before that other issue came up.

**Comment by erocheleau** [comment]
Fixed
