### ISSUE TITLE
In View event, a warning is raised regarding the "inexisting" parameter offset

### ISSUE THREAD

**Issue by obonneau** [coveo/uabot#83]
### Expected behavior
No warning should be raised
### Actual behavior
WARNING | 2017/09/18 13:40:05 Parameter offset must be a positive number in a ViewEvent+

### Steps to reproduce the behavior
create a scenario with a View event

**Comment by erocheleau** [comment]
This is not a bug, the parameter offset is meant to be there since the viewEvents will be only content from the Index. We do a search first and the view event acts as a click but with the contentIdKey/contentIdValue that is specified.
