### ISSUE TITLE
Loading a new config doesn't load the scenarios

### ISSUE THREAD

**Issue by frederic-cote23** [coveo/uabot#87]
### Context
Let’s say I want to use multiple scenario file.

My current idea is as follow:

1 - Create a Python Script that changes rename a file in a given directory to “Current.json”

2 - Have the script rotating “Current.json” for all the files inside the directory every X minutes
Ex: 0-5 min: Scenario 1 >> Current.json
5-10 min: Current.json >> Scenario 1 AND Scenario 2 >> Current.json
Etc.

3 - Modify the UA bot so that it will update its config file each minutes. To do so, I changed:

bot.continuallyRefreshScenariosEvery(1*time.Minute, conf)

### Expected behavior
The UA bot would load a new file and its Scenarios each time the refresh occurs

### Actual behavior
The UA bot load all the information excepts the Scenario, and continues running the initial scenarios.

### Steps to reproduce the behavior

1 - Set the UA  Bot refresh timer to 1 min (Line 62 of uabot.go)
2 - Start the bot targetting a specific file
3 - After the bot is running, change the content of the initial file for another one with different scenarios

The scenarios will still be the same

**Comment by francoislg** [comment]
Is it missing a `&` before `conf`?

`bot.continuallyRefreshScenariosEvery(1 * time.Minute, conf)`

**Comment by erocheleau** [comment]
Honnestly I would reject that.

This is not the design the bot was made for, if you need multiple different scenarios, start multiple bots on multiple files.

Is there a specific scenario why you need the bot to change its behavior every 5 minutes? And in that scenario why can't you just have 2 bots running with 2 different configs? Or even can you just have a script that change the config file, let the bot run for 5 minutes, then stop the bot, swap the files and re-start a bot for another 5 minutes?

The continually refresh mechanism is made so you can deploy a bot on a tool like ECS and change its config some times rarely without having to stop/restart the bot. If I had a need to have a continually updated bot, I would've made it listen to some sort of job service to pull it's config and be notified that its config has been updated.

**Comment by frederic-cote23** [comment]
That's right.

I wasn't aware of all the options you mentioned at the time of writing these lines, and I did once I started playing with the tool a bit more.

Bottom line, as of now, I'm pretty satisfied with my python script switcher :)

Cheers

**Comment by erocheleau** [comment]
So your python script is stopping the bot, swapping the files and then restarting?
