### ISSUE TITLE
Improve SearchAndClick with documentid

### ISSUE THREAD

**Issue by obonneau** [coveo/uabot#88]
Currently, the SearchAndClick feature, force a click on a document based on the "documentTitle"
Can we improve the functionality so we can select the document to click based on the "documentID" also.

**Comment by erocheleau** [comment]
Recently @jdevost changed this feature so it was a regex to find the document instead, is there a reason why you cannot use that?

**Comment by jdevost** [comment]
@obonneau You can use it like this: 
```
    "events": [{
      "type": "SearchAndClick",
      "arguments": {
        "queryText": "red willis",
        "matchField": "title",
        "matchRegex": "^RED( [0-9])?$",
        "probability": 0.95
      }
    }] 
```

**Comment by erocheleau** [comment]
I just realized you could also use this to get the uniqueID too :)

So I will close this request, feel free to re-open if you want.
